services:
  endstone:
    build: .
    container_name: endstone
    command: endstone -y
    image: endstone/endstone:latest

    ports:
      - "19132:19132/udp"

    volumes:
      - ./server:/home/endstone/bedrock_server:rw

    tty: true
    restart: unless-stopped
    stdin_open: true

    networks:
      imphnen-craft-network:
        ipv4_address: 172.100.0.2

  frp:
    build:
      context: ./frp
      dockerfile: Dockerfile

    tty: true
    restart: always

    depends_on:
      - bedrock

    networks:
      imphnen-craft-network:
        ipv4_address: 172.100.0.3

networks:
  imphnen-craft-network:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
          gateway: 172.100.0.1
